### ISSUE TITLE
中文版 3.6.6 节处翻译的小问题

### ISSUE THREAD

**Issue by xiaomx32** [xiaoweiChen/Modern-CMake-for-Cpp#1]
英文原话：“The code silently ignored the call to the standard \<regex\> header.”

对应的中文翻译：“代码静默地忽略了对标准 \<regex\> 头文件。”

读者猜测这里是漏写了，可能写为“代码静默地忽略了对标准 \<regex\> 头文件的引用。”好一点

真的很感谢您的翻译，帮助了我很多！

**Comment by xiaoweiChen** [comment]
很高兴看到我的译版对你有帮助！
也很感谢勘误，这句话确实在校对的时候，没有太注意到。
这句话应该没那么复杂，我去修改一下。
