### ISSUE TITLE
3.9 节 扩展阅读部分，第一个链接错误(404)

### ISSUE THREAD

**Issue by xiaomx32** [xiaoweiChen/Modern-CMake-for-Cpp#2]
您好，在 3.9 节扩展阅读部分，第一个链接写错了：

英文原书：https://nalexn.github.io/separation-of-concerns/
中文版(会出现 404 错误)：https://nalexn.github.io/separation-ofconcerns/

这个链接，原书上一行没写下，但实际上这个是 “-” 而不是连字符。

虽然是无关紧要的小错误，但您有时间的话，希望更正一下，谢谢您的耐心。

**Comment by xiaoweiChen** [comment]
好，多谢勘误，我白天的时候可以看一下。

我看到你那边fork了我的库，确实有问题的地方可以改完之后给我直接提PR。
这样的方式处理问题会更快一些。

**Comment by xiaomx32** [comment]
你还可以看到谁 fork 了仓库吗😂

我最近在学习 git，还不太会用 pull requests

我先在自己的本地仓库里改一下吧。

**Comment by xiaoweiChen** [comment]
哈哈，是的。这个的确能看到，是公开的。
<img width="427" alt="Screenshot 2023-01-11 093937" src="https://user-images.githubusercontent.com/2756670/211698136-9ec3c9fd-fedd-433b-a283-18e71b5e4129.png">

提PR其实是github的功能，如何给上游库创建和提交PR可以参考一下这里
https://blog.csdn.net/qq_33429968/article/details/62219783

那这个issue我就先不改了，我等你的PR吧
